### ISSUE TITLE
help running this on windows?

### ISSUE THREAD

**Issue by R3DIANCE** [mr21/killdemall#1]
hey i want to play with this on my own pc, add some new features but seems like i miss some jsext and canvasloth folders? :)

**Comment by mr21** [comment]
Hi [@R3DIANCE](https://github.com/R3DIANCE)

well idk if i could help you, that code is just too old, there is C-SDL version i dont even remember what's there is inside..
i was saying to myself that one day i should redo it with a collision library like matter.js
canvasloth is there https://github.com/mr21/canvasloth 
after idk i dnt remember
